## **Numpy** ##

In [1]:
import numpy as np

### **Range of numbers** ###

In [2]:
#Range of numbers
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### **Matrix nxn full of something** ###

In [9]:
np.full((3,3),True, dtype=bool)
np.full((3,3),1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [4]:
np.full((4,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

### **Numbers from an array that satisfy a condition** ###

In [17]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr > 5]

array([6, 7, 8, 9])

In [18]:
arr = np.array([0,1,2,3,4,5])
indexes = arr < 3
arr[indexes]

array([0, 1, 2])

### **Replacing values that met a condition in an array** ###

In [22]:
arr[arr == 5] =-1
arr

array([ 6,  7, -1,  9, 10])

In [23]:
arr = np.array([6,7,8,9,10])
arr[arr == 8] = -1
arr

array([ 6,  7, -1,  9, 10])

### **Replace numbers that met a condition without affecting the original array** ###

In [90]:
arr = np.arange(10)

# np.where(arr == conditiion, new_value, original_array)
np.where(arr % 2 == 1, -1, arr)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [26]:
arr = np.arange(16)
np.where(arr < 10, 0, arr)

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10, 11, 12, 13, 14, 15])

### **Reshaping 1 array** ###

In [31]:
arr = np.arange(15)
#arr.reshape(num_rows, num_cols)
arr.reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [34]:
arr = np.arange(10)
arr.reshape(2, -1)  # Setting to -1 automatically decides the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### **Stacking 2 arrays vertically** ###

In [32]:
a = np.arange(10).reshape(2,5)
b = np.arange(10).reshape(2,-1)

In [37]:
a.shape

(2, 5)

In [38]:
np.concatenate([a, b], axis=0) #0 is for join by column, 1 is for joining by row
#Returns a (4,5) shape


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
np.vstack([a,b]) #(4,5) shape. Joining by column. Same as np.concatenate([a, b], axis=0). Similar to append

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [43]:
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### **Stacking 2 arrays horizontally** ###

In [46]:
np.concatenate([a,b], axis=1)  #Returns a (2, 10) shape

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

In [47]:
np.hstack([a,b]) #Returns a (2, 10) shape. Creates a list of the stacked elements

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

In [48]:
np.c_[a, b]

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

###  **Create sequence of arrays** ###

In [49]:
np.repeat([6,7,8], 3) #Duplicate n times each element of the array next to each other

array([6, 6, 6, 7, 7, 7, 8, 8, 8])

In [50]:
np.repeat([1,2],5)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2])

In [68]:
np.tile([1,2,3],3) #Repeats the sequence n times one after the other on the same array

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [51]:
np.tile([9,10],3)

array([ 9, 10,  9, 10,  9, 10])

In [52]:
#Stacking vertically 2 arrays
np.vstack([
    np.repeat([6,7,8], 3)
    ,np.tile([1,2,3],3)
])

array([[6, 6, 6, 7, 7, 7, 8, 8, 8],
       [1, 2, 3, 1, 2, 3, 1, 2, 3]])

### **Finding common elements between 2 arrays** ###

In [63]:
a = np.array([1,2,3,4,5,6])
b = np.array([4,5,6,7,8,9,10])

In [57]:
np.intersect1d(a,b-1)

array([3, 4, 5, 6])

### **Remove from one array those items that exist in another** ###


In [83]:
np.setdiff1d(a,b) #Elements from a that don't exist in b
np.setdiff1d(b,a) #Elements from b that don't exist in a

array([ 7,  8,  9, 10])

### **How to get values of the first array where 2 arrays match** ###

In [64]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [66]:
a[np.where(a<b)]

array([1, 3, 3, 3, 5, 6])

In [70]:
list(set(a[np.where(a==b)])) #finding unique values existint in both lists

[2, 4]

### **Extract all numbers between a given range from a numpy array** ###

In [74]:
#Inverting a list
a = np.arange(15)[::-1]
a

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [76]:
a = np.arange(15)
a[1:4] #[start(inclusive):end(exclusive)]

array([1, 2, 3])

In [78]:
b = np.arange(15)
a[np.where((a>= 5) & (b<=10))]

array([ 5,  6,  7,  8,  9, 10])

In [79]:
a[np.where(np.logical_and(a>=5,a<=10))]

array([ 5,  6,  7,  8,  9, 10])

In [80]:
a[(a>=5) & (a<=10)]

array([ 5,  6,  7,  8,  9, 10])

### **Function that handles scalars to work on numpy arrays** ###

In [81]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

In [82]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
new_max = np.vectorize(maxx, otypes=[int])

In [83]:
new_max(a,b)

array([6, 7, 9, 8, 9, 7, 5])

In [84]:
def equal(a,b):
    if a==b:
        return a
    else:
        return 0

a = np.array([6, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 4, 1])

new_equal = np.vectorize(equal,otypes=[int])

new_equal(a,b)

array([6, 0, 0, 8, 0, 4, 0])

### **Swap two columns in a 2d numpy array** ##

In [87]:
arr = np.arange(8).reshape(-1,2)
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [88]:
arr[:,[1,0]]

array([[1, 0],
       [3, 2],
       [5, 4],
       [7, 6]])

### **Swap two rows in a 2d numpy array** ##

In [90]:
arr =np.arange(10).reshape(2,-1)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [91]:
arr[[1,0],:]

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

### **Reverse the rows of a 2D numpy array** ###

In [92]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [94]:
#Basically just orders the elements of a list, but in this case the elements itself are lists
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

### **Reverse the columns of a 2D numpy array** ###

In [100]:
arr = np.arange(9).reshape(3,3)
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [102]:
#You can do operations to the 2nd part of the shape if its an array
#We want the first 2 elements of each row
arr[:,:2]

array([[0, 1],
       [3, 4],
       [6, 7]])

### **2D array containing random floats between 5 and 10** ###

In [109]:
np.random.randint(low=5, high=9,size=(5,3)) + np.random.random((5,3))
#np.random.random((rows,columns)) gives you a random number between 0 and 1

array([[8.92682408, 7.06935468, 8.84892118],
       [6.34607546, 8.42078302, 5.27787931],
       [8.38262586, 8.89635386, 8.26634076],
       [6.41831796, 6.84469709, 6.55812776],
       [6.57920748, 8.58478131, 7.04847435]])

In [108]:
np.random.uniform(5,10, size=(5,3))

array([[6.59324772, 6.99876651, 7.96080439],
       [9.83317324, 9.47577985, 7.7631405 ],
       [7.35595859, 7.85518857, 8.40944115],
       [7.25475441, 6.96595653, 9.23780654],
       [5.12818277, 9.93474326, 5.80931313]])

### **Supress scientific notation** ###

In [112]:
np.set_printoptions(suppress=True)

np.random.random((5,3)) / 1e3

array([[0.00003473, 0.00003414, 0.00047243],
       [0.00006026, 0.00048233, 0.00032684],
       [0.00032659, 0.00045449, 0.0006462 ],
       [0.00037975, 0.00095019, 0.0003241 ],
       [0.00070535, 0.00007819, 0.00014565]])

### **Convert a 1d array of tuples to a 2d numpy array** ###

In [116]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
iris_1d[:10]

/var/folders/8q/9zk58sl93rx81t6np6mvjx200000gn/T/ipykernel_3992/4113451106.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)


array([(5.1, 3.5, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, b'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, b'Iris-setosa'),
       (4.6, 3.1, 1.5, 0.2, b'Iris-setosa'),
       (5. , 3.6, 1.4, 0.2, b'Iris-setosa'),
       (5.4, 3.9, 1.7, 0.4, b'Iris-setosa'),
       (4.6, 3.4, 1.4, 0.3, b'Iris-setosa'),
       (5. , 3.4, 1.5, 0.2, b'Iris-setosa'),
       (4.4, 2.9, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3.1, 1.5, 0.1, b'Iris-setosa')],
      dtype=[('f0', '<f8'), ('f1', '<f8'), ('f2', '<f8'), ('f3', '<f8'), ('f4', 'S15')])

In [120]:
np.array([row.tolist()[:4] for row in iris_1d])[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

### **Normalize an array** ###

In [121]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
sepallength

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [124]:
((sepallength - sepallength.min()) / (sepallength.max() - sepallength.min()))[:5]

array([0.22222222, 0.16666667, 0.11111111, 0.08333333, 0.19444444])