## **Numpy** ##

In [1]:
import numpy as np

### **Range of numbers** ###

In [2]:
#Range of numbers
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### **Matrix nxn full of something** ###

In [9]:
np.full((3,3),True, dtype=bool)
np.full((3,3),1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [4]:
np.full((4,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

### **Numbers from an array that satisfy a condition** ###

In [17]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr > 5]

array([6, 7, 8, 9])

In [18]:
arr = np.array([0,1,2,3,4,5])
indexes = arr < 3
arr[indexes]

array([0, 1, 2])

### **Replacing values that met a condition in an array** ###

In [22]:
arr[arr == 5] =-1
arr

array([ 6,  7, -1,  9, 10])

In [23]:
arr = np.array([6,7,8,9,10])
arr[arr == 8] = -1
arr

array([ 6,  7, -1,  9, 10])

### **Replace numbers that met a condition without affecting the original array** ###

In [90]:
arr = np.arange(10)

# np.where(arr == conditiion, new_value, original_array)
np.where(arr % 2 == 1, -1, arr)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [26]:
arr = np.arange(16)
np.where(arr < 10, 0, arr)

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10, 11, 12, 13, 14, 15])

### **Reshaping 1 array** ###

In [31]:
arr = np.arange(15)
#arr.reshape(num_rows, num_cols)
arr.reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [34]:
arr = np.arange(10)
arr.reshape(2, -1)  # Setting to -1 automatically decides the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### **Stacking 2 arrays vertically** ###

In [32]:
a = np.arange(10).reshape(2,5)
b = np.arange(10).reshape(2,-1)

In [37]:
a.shape

(2, 5)

In [38]:
np.concatenate([a, b], axis=0) #0 is for join by column, 1 is for joining by row
#Returns a (4,5) shape


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
np.vstack([a,b]) #(4,5) shape. Joining by column. Same as np.concatenate([a, b], axis=0). Similar to append

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [43]:
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### **Stacking 2 arrays horizontally** ###

In [46]:
np.concatenate([a,b], axis=1)  #Returns a (2, 10) shape

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

In [47]:
np.hstack([a,b]) #Returns a (2, 10) shape. Creates a list of the stacked elements

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

In [48]:
np.c_[a, b]

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

###  **Create sequence of arrays** ###

In [49]:
np.repeat([6,7,8], 3) #Duplicate n times each element of the array next to each other

array([6, 6, 6, 7, 7, 7, 8, 8, 8])

In [50]:
np.repeat([1,2],5)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2])

In [68]:
np.tile([1,2,3],3) #Repeats the sequence n times one after the other on the same array

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [51]:
np.tile([9,10],3)

array([ 9, 10,  9, 10,  9, 10])

In [52]:
#Stacking vertically 2 arrays
np.vstack([
    np.repeat([6,7,8], 3)
    ,np.tile([1,2,3],3)
])

array([[6, 6, 6, 7, 7, 7, 8, 8, 8],
       [1, 2, 3, 1, 2, 3, 1, 2, 3]])

### **Finding common elements between 2 arrays** ###

In [63]:
a = np.array([1,2,3,4,5,6])
b = np.array([4,5,6,7,8,9,10])

In [57]:
np.intersect1d(a,b-1)

array([3, 4, 5, 6])

### **Remove from one array those items that exist in another** ###


In [83]:
np.setdiff1d(a,b) #Elements from a that don't exist in b
np.setdiff1d(b,a) #Elements from b that don't exist in a

array([ 7,  8,  9, 10])

### **How to get values of the first array where 2 arrays match** ###

In [64]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [66]:
a[np.where(a<b)]

array([1, 3, 3, 3, 5, 6])

In [70]:
list(set(a[np.where(a==b)])) #finding unique values existint in both lists

[2, 4]

### **Extract all numbers between a given range from a numpy array** ###

In [74]:
#Inverting a list
a = np.arange(15)[::-1]
a

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [76]:
a = np.arange(15)
a[1:4] #[start(inclusive):end(exclusive)]

array([1, 2, 3])

In [78]:
b = np.arange(15)
a[np.where((a>= 5) & (b<=10))]

array([ 5,  6,  7,  8,  9, 10])

In [79]:
a[np.where(np.logical_and(a>=5,a<=10))]

array([ 5,  6,  7,  8,  9, 10])

In [80]:
a[(a>=5) & (a<=10)]

array([ 5,  6,  7,  8,  9, 10])

### **Function that handles scalars to work on numpy arrays** ###

In [81]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

In [82]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
new_max = np.vectorize(maxx, otypes=[int])

In [83]:
new_max(a,b)

array([6, 7, 9, 8, 9, 7, 5])

In [84]:
def equal(a,b):
    if a==b:
        return a
    else:
        return 0

a = np.array([6, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 4, 1])

new_equal = np.vectorize(equal,otypes=[int])

new_equal(a,b)

array([6, 0, 0, 8, 0, 4, 0])

### **Swap two columns in a 2d numpy array** ##

In [87]:
arr = np.arange(8).reshape(-1,2)
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [88]:
arr[:,[1,0]]

array([[1, 0],
       [3, 2],
       [5, 4],
       [7, 6]])

### **Swap two rows in a 2d numpy array** ##

In [90]:
arr =np.arange(10).reshape(2,-1)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [91]:
arr[[1,0],:]

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

### **Reverse the rows of a 2D numpy array** ###

In [92]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [94]:
#Basically just orders the elements of a list, but in this case the elements itself are lists
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

### **Reverse the columns of a 2D numpy array** ###

In [100]:
arr = np.arange(9).reshape(3,3)
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [102]:
#You can do operations to the 2nd part of the shape if its an array
#We want the first 2 elements of each row
arr[:,:2]

array([[0, 1],
       [3, 4],
       [6, 7]])

### **2D array containing random floats between 5 and 10** ###

In [109]:
np.random.randint(low=5, high=9,size=(5,3)) + np.random.random((5,3))
#np.random.random((rows,columns)) gives you a random number between 0 and 1

array([[8.92682408, 7.06935468, 8.84892118],
       [6.34607546, 8.42078302, 5.27787931],
       [8.38262586, 8.89635386, 8.26634076],
       [6.41831796, 6.84469709, 6.55812776],
       [6.57920748, 8.58478131, 7.04847435]])

In [108]:
np.random.uniform(5,10, size=(5,3))

array([[6.59324772, 6.99876651, 7.96080439],
       [9.83317324, 9.47577985, 7.7631405 ],
       [7.35595859, 7.85518857, 8.40944115],
       [7.25475441, 6.96595653, 9.23780654],
       [5.12818277, 9.93474326, 5.80931313]])

### **Supress scientific notation** ###

In [112]:
np.set_printoptions(suppress=True)

np.random.random((5,3)) / 1e3

array([[0.00003473, 0.00003414, 0.00047243],
       [0.00006026, 0.00048233, 0.00032684],
       [0.00032659, 0.00045449, 0.0006462 ],
       [0.00037975, 0.00095019, 0.0003241 ],
       [0.00070535, 0.00007819, 0.00014565]])

### **Convert a 1d array of tuples to a 2d numpy array** ###

In [116]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
iris_1d[:10]

/var/folders/8q/9zk58sl93rx81t6np6mvjx200000gn/T/ipykernel_3992/4113451106.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)


array([(5.1, 3.5, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, b'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, b'Iris-setosa'),
       (4.6, 3.1, 1.5, 0.2, b'Iris-setosa'),
       (5. , 3.6, 1.4, 0.2, b'Iris-setosa'),
       (5.4, 3.9, 1.7, 0.4, b'Iris-setosa'),
       (4.6, 3.4, 1.4, 0.3, b'Iris-setosa'),
       (5. , 3.4, 1.5, 0.2, b'Iris-setosa'),
       (4.4, 2.9, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3.1, 1.5, 0.1, b'Iris-setosa')],
      dtype=[('f0', '<f8'), ('f1', '<f8'), ('f2', '<f8'), ('f3', '<f8'), ('f4', 'S15')])

In [120]:
np.array([row.tolist()[:4] for row in iris_1d])[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

### **Normalize an array** ###

In [121]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
sepallength

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [124]:
((sepallength - sepallength.min()) / (sepallength.max() - sepallength.min()))[:5]

array([0.22222222, 0.16666667, 0.11111111, 0.08333333, 0.19444444])

### **Compute softmax for every item in the array** ###

In [125]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.array([float(row[0]) for row in iris])

In [127]:
def softmax(x):
    e_x = np.exp(x-np.max(x))
    return e_x / e_x.sum(axis=0) #Axis 0 sums by column, axis 1 sums by row

print(softmax(sepallength)[:10])

[0.00221959 0.00181724 0.00148783 0.00134625 0.00200836 0.00299613
 0.00134625 0.00200836 0.00110221 0.00181724]


### **Insert values at random positions** ###

In [139]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

In [ ]:
i, j = np.where(iris_2d) #returns indexes of all non-zero values
iris_2d[np.random.choice((i),20),np.random.choice((j),20)] = np.nan 
iris_2d


### **Find the position of null values** ###

In [159]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan


In [161]:
np.where(np.isnan(iris_2d))

(array([  3,  14,  16,  18,  32,  33,  67,  78,  86,  89,  97, 101, 106,
        118, 121, 128, 128, 140, 142, 143]),
 array([0, 0, 2, 2, 0, 3, 2, 0, 2, 2, 3, 1, 2, 1, 2, 1, 2, 0, 3, 2]))

### **Drop rows with a missing value** ###

In [174]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [185]:
iris_2d[[~np.any(np.isnan(row)) for row in iris_2d]][:5] #Any checks if there's any True in the row

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5.4, 3.9, 1.7, 0.4]])

### **Correlation between 2 columns of a numpy array** ###

In [187]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [193]:
np.corrcoef(iris[:,0],iris[:,1])

array([[ 1.        , -0.10936925],
       [-0.10936925,  1.        ]])

### **Find if an array has null values** ###

In [194]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [198]:
np.isnan(iris_2d).sum() > 0
np.isnan(iris_2d).any()

False

### **Replace null values with a 0** ###

In [250]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [203]:
iris_2d[np.isnan(iris_2d)] = 0

### **Count of unique values in an array** ###

In [204]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [210]:
a = np.unique(iris[:,4],return_counts=True)[0]


array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
      dtype=object)

### **Mapping an array** ###

In [214]:
dict_ = {'a':1, 'b':2, 'c':3}
b = np.array(['a','b','c'])

[dict_[v] for v in b]

[1, 2, 3]

### **Adding a new column to an array** ###

In [ ]:
newCol = np.full((150,1),1.0)
np.hstack([iris_2d,newCol])

### **Probabilistic sampling** ###

In [230]:
a = np.array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])
np.random.choice(a, 10, p=[0.5,0.25,0.25])

array(['Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor'], dtype='<U15')

### **Sort a 2d array by a column** ###

In [244]:
# (len(iris[:,0]) - 1) -  iris[:,0].argsort()  backwards
order = iris[:,0].argsort()
order

array([ 13,  42,  38,   8,  41,  22,   3,   6,  47,   2,  29,  12,  45,
        24,  11,  30,  57, 106,  34,   9,  37,   1,  40,  26,  49,  35,
        43,  60,   7,  93,   4,  25,  44,  46,  98,   0,  39,  17,  23,
        21,  19,  32,  28,  27,  59,  48,  84,   5,  20,  31,  10,  16,
        36,  90,  33,  53,  81,  80,  89,  88, 121,  66,  69,  94,  64,
        79,  96,  99,  15,  55, 113,  18,  95,  67,  14,  92, 114, 142,
        82, 101, 149,  61,  70,  78,  83, 138,  85,  62, 119, 127, 134,
        71,  63,  73,  91,  68,  97, 148, 126,  72, 123, 146,  56, 133,
       100,  87, 136, 103, 132, 128, 137,  51, 115,  74, 111, 104, 116,
       147,  54, 110,  58,  75,  86, 140, 108,  77,  65, 144, 145, 124,
       143,  76, 112, 139, 141,  52, 120,  50, 102, 129, 125, 109, 107,
       130, 105, 122, 118, 117, 135, 131])

In [247]:
iris[order,:][:20]

array([[b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [b'4.4', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.4', b'3.0', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.5', b'2.3', b'1.3', b'0.3', b'Iris-setosa'],
       [b'4.6', b'3.6', b'1.0', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'4.6', b'3.2', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.0', b'1.4', b'0.1', b'Iris-setosa'],
       [b'4.8', b'3.0', b'1.4', b'0.3', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.9', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.1', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.9', b'2.4', b'3.3', b'1.0', b'Iris-versicolor'],
       [b'4.9', b'2.5', b'4

### **Find the most common value in an array** ###

In [253]:
v, c = np.unique(iris_2d[:,2],return_counts=True)
v, c

(array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.9, 3. , 3.3, 3.5, 3.6,
        3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9,
        5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.3,
        6.4, 6.6, 6.7, 6.9, nan]),
 array([ 1,  1,  2,  7, 10, 14,  7,  4,  2,  1,  2,  1,  1,  1,  1,  3,  5,
         3,  4,  2,  4,  8,  3,  5,  4,  5,  3,  8,  2,  2,  2,  3,  6,  3,
         2,  2,  2,  3,  1,  1,  1,  1,  1,  6]))

In [255]:
v[np.argmax(c)]

1.5

### **Find the position of the first occurrence of a value greater than a given value** ###

In [263]:
np.argwhere(iris[:,3].astype(float) > 1.0)[0]  #Argwhere finds the indexes of values in the array that meet the condition

array([50])

### **Filter elements of the array that are within a range** ###

In [264]:
np.set_printoptions(precision=2)
np.random.seed(100)
a = np.random.uniform(1,50, 20)

In [266]:
a[np.where((a>10) & (a<30))]

array([27.63, 14.64, 21.8 , 29.18, 11.25, 10.08, 11.77, 14.43])

### **Top N values from an array** ###

In [271]:
a = np.random.uniform(1,50, 20)
a[a.argsort()][-5:] #last 5 values until the end

array([43.12, 46.25, 47.72, 48.85, 49.14])

### **Array of arrays into a flat 1d array** ###

In [272]:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])

/var/folders/8q/9zk58sl93rx81t6np6mvjx200000gn/T/ipykernel_3992/560290888.py:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array_of_arrays = np.array([arr1, arr2, arr3])


In [277]:
np.concatenate([arr1,arr2,arr3],axis=0)
np.concatenate(array_of_arrays)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])